/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
import * as import0 from '../../../../../../../../app/home/components/component1/1.component';
import * as import1 from '@angular/core/src/linker/view';
import * as import3 from '@angular/core/src/linker/view_utils';
import * as import7 from '@angular/core/src/linker/component_factory';
import * as import10 from '@angular/core/src/linker/view_container';
import * as import14 from '../../directives/my.directive.ngfactory';
import * as import15 from '../../directives/popover.directive.ngfactory';
export declare class Wrapper_Component1 {
    _eventHandler: Function;
    context: import0.Component1;
    _changed: boolean;
    constructor(p0: any);
    ngOnDetach(view: import1.AppView<any>, componentView: import1.AppView<any>, el: any): void;
    ngOnDestroy(): void;
    ngDoCheck(view: import1.AppView<any>, el: any, throwOnChange: boolean): boolean;
    checkHost(view: import1.AppView<any>, componentView: import1.AppView<any>, el: any, throwOnChange: boolean): void;
    handleEvent(eventName: string, $event: any): boolean;
    subscribe(view: import1.AppView<any>, _eventHandler: any): void;
}
export declare const Component1NgFactory: import7.ComponentFactory<import0.Component1>;
export declare class View_Component10 extends import1.AppView<import0.Component1> {
    _el_0: any;
    _text_1: any;
    _text_2: any;
    _el_3: any;
    _text_4: any;
    _text_5: any;
    _anchor_6: any;
    _vc_6: import10.ViewContainer;
    _TemplateRef_6_5: any;
    _MyDirectiveDirective_6_6: import14.Wrapper_MyDirectiveDirective;
    _text_7: any;
    _el_8: any;
    _vc_8: import10.ViewContainer;
    _PopoverDirective_8_5: import15.Wrapper_PopoverDirective;
    _text_9: any;
    _text_10: any;
    constructor(viewUtils: import3.ViewUtils, parentView: import1.AppView<any>, parentIndex: number, parentElement: any);
    createInternal(rootSelector: string): import7.ComponentRef<any>;
    injectorGetInternal(token: any, requestNodeIndex: number, notFoundResult: any): any;
    detectChangesInternal(throwOnChange: boolean): void;
    destroyInternal(): void;
    createEmbeddedViewInternal(nodeIndex: number): import1.AppView<any>;
    handleEvent_3(eventName: string, $event: any): boolean;
    handleEvent_8(eventName: string, $event: any): boolean;
}
